### ISSUE TITLE
Store metadata in etcd

### ISSUE THREAD

**Issue by zaibon** [zero-os/0-stor-lib#18]
## Goal: 
Store the metadata produce by the lib (configuration of the lib, spreading of the blocks, ...) to [etcd](https://github.com/coreos/etcd)

Check [principles](https://github.com/zero-os/0-stor-lib/blob/master/specs/principles.md#pseudo-language-to-use-lib-example-in-python) for examples.

**Comment by iwanbk** [comment]
moved to 0-stor
