### ISSUE TITLE
create specs/docs for this lib

### ISSUE THREAD

**Issue by despiegk** [zero-os/0-stor-lib#2]

**Comment by despiegk** [comment]
e.g. what is metadata like when info uploaded

**Comment by zaibon** [comment]
@despiegk 
Questions :
- in principles.md there is `policy.setShard(["http://192.168.66.10:3000/bpath/",...]) #21 locations (always at least 1 more than distr nr + redundancy)`
What does this supposed to do ?

 ```
policy.replication_maxsize=1024 #expressed in kb, if small than this then will be X way replication
policy.replication_nr = 3 #e.g. 3 way replication
policy.distribution_nr = 16 #means will cut into 16 EC pieces
policy.distribution_redundancy = 4# means will store 4 additional on top of 16
```
- I need more detail about replication and distribution there.


- In  the example code the `put` method of the client takes a path. What is this path ? We should be more generic and support any byte stream instead, no ?

**Comment by zaibon** [comment]
Link to the specs/requirements: https://github.com/zero-os/0-stor-lib/blob/master/specs/requirements.md

Still WIP

**Comment by iwanbk** [comment]
moved to 0-stor
