### ISSUE TITLE
Need basic communication primitive for the 0-stor

### ISSUE THREAD

**Issue by zaibon** [zero-os/0-stor-lib#22]
We need to have some basic method to talk to the 0-stor over its REST API.

**Comment by iwanbk** [comment]
depends on https://github.com/zero-os/0-stor/issues/50

**Comment by iwanbk** [comment]
From reading the https://rawgit.com/zero-os/0-stor/master/specs/raml/sdstor.html# (oh, it was much easier than read the raml directly), the flow to store data is:
- create namespace 
- create reservation for the created namespace (not sure whether this is optional or not)
- call POST  /namespaces/{nsid}/objects to store and GET to retrieve

**Comment by iwanbk** [comment]
moved to 0-stor
