### ISSUE TITLE
question: implementation language in golang only?

### ISSUE THREAD

**Issue by despiegk** [zero-os/0-stor-lib#4]
- maybe we should re-implement only using golang (erasure coding is already in tlogserver)
- implement as lib
- also create command line client using this lib (then python can use this one for now)

**Comment by zaibon** [comment]
I would love to have the implementation in go only. having a part of the lib in C is hard to maintain and enforce certain detail implementation because of the binding.

**Comment by zaibon** [comment]
Implementation will be in golang
